export const categoriesData = [
  {
    name: 'Xe Đô Thị & Cỡ Nhỏ',
    description: 'Các dòng xe điện đô thị cá tính, linh hoạt và xe thương mại nhỏ gọn (VF 3, VF 5 Plus, VF e34, EC Van).',
    image: '',
  },
  {
    name: 'SUV Cỡ Vừa',
    description: 'Các mẫu SUV & Crossover điện cỡ vừa thời thượng, năng động (VF 6, VF 7).',
    image: '',
  },
  {
    name: 'SUV Cỡ Lớn & Hạng Sang',
    description: 'Dòng SUV điện cao cấp đẳng cấp toàn cầu, không gian rộng rãi và công nghệ ADAS tiên tiến (VF 8, VF 9).',
    image: '',
  },
  {
    name: 'Bán Tải & Xe Đột Phá',
    description: 'Mẫu xe bán tải điện thể thao đa dụng, phong cách tự do phóng khoáng (VF Wild).',
    image: '',
  },
];

export const productsData = [
  {
    name: 'VinFast VF 3',
    price: 240000000,
    originalPrice: 322000000,
    description: 'VinFast VF 3 là mẫu xe điện Mini e-SUV đô thị cá tính, linh hoạt với thiết kế vuông vức mạnh mẽ, khoảng sáng gầm xe 191mm, trang bị màn hình giải trí 10 inch hiện đại.',
    image: '',
    images: [],
    stock: 15,
    engine: 'Pin LFP 18.6 kWh - 43 hp - Quãng đường 210 km',
    color: 'Vàng / Nội thất Đen',
    isFeatured: true,
    categoryName: 'Xe Đô Thị & Cỡ Nhỏ',
  },
  {
    name: 'VinFast VF 5 Plus',
    price: 468000000,
    originalPrice: 548000000,
    description: 'VinFast VF 5 Plus thuộc phân khúc SUV Hạng A thời thượng, trẻ trung, được trang bị gói công nghệ an toàn ADAS cơ bản và trợ lý ảo thông minh ViVi.',
    image: '',
    images: [],
    stock: 12,
    engine: 'Pin Ternary 37.23 kWh - 134 hp - Quãng đường 326 km',
    color: 'Cam / Nội thất Đen-Cam',
    isFeatured: true,
    categoryName: 'Xe Đô Thị & Cỡ Nhỏ',
  },
  {
    name: 'VinFast VF e34',
    price: 710000000,
    originalPrice: 830000000,
    description: 'VinFast VF e34 là mẫu Crossover điện thông minh đầu tiên tiên phong của VinFast tại Việt Nam, sở hữu khả năng vận hành êm ái và không gian rộng rãi.',
    image: '',
    images: [],
    stock: 10,
    engine: 'Pin LFP 42 kWh - 147 hp - Quãng đường 318.6 km',
    color: 'Xanh Lá Tươi / Nội thất Đen',
    isFeatured: false,
    categoryName: 'Xe Đô Thị & Cỡ Nhỏ',
  },
  {
    name: 'VinFast VF 6 Eco',
    price: 675000000,
    originalPrice: 765000000,
    description: 'VinFast VF 6 Eco sở hữu thiết kế thời thượng từ Torino Design, trang bị màn hình 12.9 inch sắc nét và động cơ điện vận hành kinh tế.',
    image: '',
    images: [],
    stock: 8,
    engine: 'Pin LFP 59.6 kWh - 174 hp - Quãng đường 399 km',
    color: 'Trắng Pearl / Nội thất Đen',
    isFeatured: false,
    categoryName: 'SUV Cỡ Vừa',
  },
  {
    name: 'VinFast VF 6 Plus',
    price: 765000000,
    originalPrice: 855000000,
    description: 'VinFast VF 6 Plus được thiết kế bởi Torino Design mang phong cách kiệt tác dòng SUV Hạng B, động cơ 201 mã lực mạnh mẽ vượt trội trong phân khúc.',
    image: '',
    images: [],
    stock: 10,
    engine: 'Pin LFP 59.6 kWh - 201 hp - Quãng đường 381 km',
    color: 'Đỏ VinFast / Nội thất Đen',
    isFeatured: true,
    categoryName: 'SUV Cỡ Vừa',
  },
  {
    name: 'VinFast VF 7 Eco',
    price: 850000000,
    originalPrice: 999000000,
    description: 'VinFast VF 7 Eco mang tinh thần phi thuyền vũ trụ hiện đại, kích thước gầm cao thể thao cùng khoang lái số hóa mượt mà.',
    image: '',
    images: [],
    stock: 7,
    engine: 'Pin LFP 75.3 kWh - 201 hp - Quãng đường 450 km',
    color: 'Bạc Desat / Nội thất Đen',
    isFeatured: false,
    categoryName: 'SUV Cỡ Vừa',
  },
  {
    name: 'VinFast VF 7 Plus',
    price: 999000000,
    originalPrice: 1199000000,
    description: 'VinFast VF 7 Plus sở hữu ngôn ngữ thiết kế "Vũ trụ phi thuyền" đầy cảm hứng, hệ dẫn động 2 cầu toàn thời gian AWD, khả năng tăng tốc từ 0-100 km/h chỉ trong 5.8 giây.',
    image: '',
    images: [],
    stock: 8,
    engine: '2 Động cơ Điện AWD 349 hp - Pin 75.3 kWh - Quãng đường 431 km',
    color: 'Xám Graphene / Nội thất Đen',
    isFeatured: true,
    categoryName: 'SUV Cỡ Vừa',
  },
  {
    name: 'VinFast VF 8 Eco',
    price: 1090000000,
    originalPrice: 1290000000,
    description: 'VinFast VF 8 Eco là mẫu SUV điện cỡ trung sang trọng, đạt tiêu chuẩn an toàn 5 sao ASEAN NCAP & EURO NCAP.',
    image: '',
    images: [],
    stock: 9,
    engine: '2 Động cơ Điện AWD 349 hp - Pin 88.3 kWh - Quãng đường 471 km',
    color: 'Đen Jet Black / Nội thất Đen',
    isFeatured: false,
    categoryName: 'SUV Cỡ Lớn & Hạng Sang',
  },
  {
    name: 'VinFast VF 8 Plus',
    price: 1270000000,
    originalPrice: 1470000000,
    description: 'VinFast VF 8 Plus là mẫu SUV điện cỡ trung đẳng cấp toàn cầu, trang bị cửa sổ trời toàn cảnh panorama, hệ thống lái tự động thông minh Cấp độ 2 ADAS.',
    image: '',
    images: [],
    stock: 6,
    engine: '2 Động cơ Điện AWD 402 hp - Pin 88.3 kWh - Quãng đường 447 km',
    color: 'Xanh Dương Deep Ocean / Nội thất Nâu',
    isFeatured: true,
    categoryName: 'SUV Cỡ Lớn & Hạng Sang',
  },
  {
    name: 'VinFast VF 9 Eco',
    price: 1491000000,
    originalPrice: 1990000000,
    description: 'VinFast VF 9 Eco là mẫu SUV điện 7 chỗ cỡ lớn bề thế, công suất 402 mã lực, quãng đường di chuyển lên tới 602 km sau mỗi lần sạc đầy.',
    image: '',
    images: [],
    stock: 4,
    engine: '2 Động cơ Điện AWD 402 hp - Pin 123 kWh - Quãng đường 602 km',
    color: 'Xanh Rêu VinFast / Nội thất Đen',
    isFeatured: false,
    categoryName: 'SUV Cỡ Lớn & Hạng Sang',
  },
  {
    name: 'VinFast VF 9 Plus',
    price: 1690000000,
    originalPrice: 2190000000,
    description: 'VinFast VF 9 Plus là mẫu SUV điện 7 chỗ Full-Size hạng sang đại diện cho đỉnh cao công nghệ và sang trọng của VinFast, trang bị ghế cơ trưởng massage, sưởi và thông gió.',
    image: '',
    images: [],
    stock: 5,
    engine: '2 Động cơ Điện AWD 402 hp - Pin 123 kWh - Quãng đường 626 km',
    color: 'Đen VinFast / Nội thất Trắng',
    isFeatured: true,
    categoryName: 'SUV Cỡ Lớn & Hạng Sang',
  },
  {
    name: 'VinFast VF Wild',
    price: 950000000,
    originalPrice: 1150000000,
    description: 'VinFast VF Wild là mẫu xe bán tải điện concept đột phá, kích thước bề thế 5.3m, thùng sau mở rộng thông minh lên cabin.',
    image: '',
    images: [],
    stock: 3,
    engine: '2 Động cơ Điện AWD 402 hp - Pin 100 kWh - Quãng đường 450 km',
    color: 'Xám Titan / Nội thất Da Bò',
    isFeatured: true,
    categoryName: 'Bán Tải & Xe Đột Phá',
  },
  {
    name: 'VinFast EC Van',
    price: 380000000,
    originalPrice: 450000000,
    description: 'VinFast EC Van là dòng xe Van điện đô thị nhỏ gọn, tối ưu khoang chứa hàng kinh doanh và dịch vụ vận chuyển thông minh.',
    image: '',
    images: [],
    stock: 10,
    engine: 'Pin LFP 28 kWh - 60 hp - Quãng đường 180 km',
    color: 'Trắng Đô Thị / Nội thất Đen',
    isFeatured: false,
    categoryName: 'Xe Đô Thị & Cỡ Nhỏ',
  },
];



