export const categoriesData = [
  {
    name: 'Pod System',
    description: 'Thiết bị nhỏ gọn, thông minh, chuyên dùng với tinh dầu Saltnic nồng độ ni cao.',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Vape Kit',
    description: 'Các bộ sản phẩm công suất lớn, tạo nhiều khói, chơi vị Freebase cực đỉnh.',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Juice Saltnic',
    description: 'Tinh dầu nồng độ nicotine cao (30mg - 50mg) mang lại cảm giác đầm vị, thỏa mãn.',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Juice Freebase',
    description: 'Tinh dầu nồng độ nicotine thấp (3mg - 6mg) nhiều khói, hương vị hoa quả thanh mát.',
    image: 'https://images.unsplash.com/photo-1511389026070-a14ae610a1be?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Phụ Kiện',
    description: 'Đầu Pod thay thế, Occ thay thế, dây đeo và pin chuyên dụng chính hãng.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
  },
];

export const productsData = [
  {
    name: 'OXVA Xlim Pro 30W Kit',
    price: 650000,
    originalPrice: 750000,
    description: 'Phiên bản Xlim Pro đỉnh cao của nhà OXVA với công suất 30W, dung lượng pin 1000mAh và dải đèn RGB lấp lánh sang trọng.',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=600&q=80',
    stock: 50,
    brand: 'OXVA',
    nicotine: 'Tương thích 0.6 / 0.8 ohm',
    flavor: 'Black Gold / Carbon Fiber',
    isFeatured: true,
    categorySlug: 'pod-system',
  },
  {
    name: 'Aspire Flexus Peak',
    price: 480000,
    originalPrice: 550000,
    description: 'Aspire Flexus Peak mang thiết kế cực kỳ hiện đại với vỏ trong suốt lộ mạch điện tử, pin 1000mAh, sạc nhanh Type-C 2A.',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=600&q=80',
    stock: 35,
    brand: 'Aspire',
    nicotine: 'Tương thích AF Mesh Coil',
    flavor: 'Amber / Teal / Obsidian Black',
    isFeatured: true,
    categorySlug: 'pod-system',
  },
  {
    name: 'Lost Vape Ursa Nano 2',
    price: 380000,
    originalPrice: 420000,
    description: 'Thiết kế họa tiết Cyberpunk phát sáng độc đáo từ Lost Vape. Dung lượng pin 900mAh và cần gạt gió chỉnh linh hoạt.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    stock: 20,
    brand: 'Lost Vape',
    nicotine: '0.8 ohm',
    flavor: 'Cyber Storm / Phantom City',
    isFeatured: false,
    categorySlug: 'pod-system',
  },
  {
    name: 'Tokyo Juice Super Cool Melon 30ml',
    price: 320000,
    originalPrice: 350000,
    description: 'Tinh dầu dưa hấu siêu lạnh từ Tokyo Juice. Độ ngọt vừa phải kết hợp với cảm giác mát lạnh cực đã ở cuống họng.',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    stock: 100,
    brand: 'Tokyo Juice',
    nicotine: '35mg',
    flavor: 'Dưa Hấu Lạnh',
    isFeatured: true,
    categorySlug: 'juice-saltnic',
  },
  {
    name: '1982 Ice Grape 30ml',
    price: 330000,
    originalPrice: 360000,
    description: 'Huyền thoại vị nho lạnh thơm ngọt đậm đà, ni đầm sâu tạo cảm giác thư giãn tuyệt đối cho người sử dụng.',
    image: 'https://images.unsplash.com/photo-1511389026070-a14ae610a1be?auto=format&fit=crop&w=600&q=80',
    stock: 80,
    brand: '1982',
    nicotine: '50mg',
    flavor: 'Nho Lạnh',
    isFeatured: true,
    categorySlug: 'juice-saltnic',
  },
  {
    name: 'Nasty Juice Cush Man Xoài Lạnh 60ml',
    price: 350000,
    originalPrice: 380000,
    description: 'Tinh dầu freebase vị xoài chín ngọt lịm đặc trưng của nhà Nasty Juice, công thức khói dày đặc phù hợp với Vape công suất lớn.',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    stock: 45,
    brand: 'Nasty Juice',
    nicotine: '3mg',
    flavor: 'Xoài Lạnh',
    isFeatured: false,
    categorySlug: 'juice-freebase',
  },
  {
    name: 'Đầu Pod thay thế Xlim V3 0.6 ohm',
    price: 80000,
    originalPrice: 90000,
    description: 'Đầu pod Xlim V3 nắp châm dầu bên hông (Top-fill) chống rò rỉ tinh dầu cực tốt, lõi Mesh coil 0.6 ohm cho hương vị hoàn hảo.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    stock: 300,
    brand: 'OXVA',
    nicotine: '0.6 ohm',
    flavor: 'Chuyên vị / Khói vừa',
    isFeatured: false,
    categorySlug: 'accessories',
  },
];
